name: Test code
run-name: ${{ github.actor }} is running the test suite.
on:
  push:
    branches: [main]
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Typecheck
        run: yarn run check
      - name: Lint
        run: yarn run lint
      - name: Unit tests
        run: yarn run test:unit
      - name: Playwright tests
        run: yarn run test
